type Plant{
    id: ID,
    name: String,
    description: String,
    price: Float,
    category: String,
    quantity: Int,
    typeOfPlant: String,
    sunlightRequirements: String,
    wateringFrequency: String,
}
type Planter{
    id: ID,
    name: String,
    description: String,
    price: Float,
    category: String,
    quantity: Int,
    material: String,
    dimensions: String,
    color: String,
}
type Seed{
    id: ID,
    name: String,
    description: String,
    price: Float,
    category: String,
    quantity: Int,
    seedType: String,
    germinationTime: Int,
    season: String,
}
type Query{
    getAllPlants:[Plant]
    getPlantById(id: Int): Plant
    getAllPlanters:[Planter]
    getPlanterById(id: Int): Planter
    getAllSeeds:[Seed]
    getSeedById(id: Int): Seed
}
type Mutation {
    updatePlant(
        id: Int,
        name: String,
        description: String,
        price: Float,
        category: String,
        quantity: Int,
        typeOfPlant: String,
        sunlightRequirements: String,
        wateringFrequency: String
    ): String
}
